### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Cait43**

### CODE REVIEW

**Review by d-hmlton — COMMENTED** [review]
_(Reviewing latest commit of code as of Monday 10:39am)_
Code meets the parameters defined in the brief! The Die() method is called DiceRoll() and not Roll() as defined in the brief, but I'm sure this doesn't matter.
I like that the Game() functions all take place within Testing() - for my code, I ran Game() and Testing() separately, but this seems more efficient. I noticed that the main program creates a Game object, but never calls it's methods, so it seems to be redundant - probably safe to delete?
For further improvement, add XML commenting as described in the CRG. _("XML documenting comments are throughout the code.")_ Well done! 👍

**Review by Mr-X1214 — COMMENTED** [review]
In the die class you could put a comment to explain what the Random r = new Random(); is for to show more understanding of it and make it easier for other people to understand it too. Naming conventions have been stuck to.

In the game class you could put a comment to say what public int GameRolls() will do. It would be better to use camalCase for SumOfDie as it looks to be a local variable. Last of all, you could add some comments to line 36 to 41 to explain what that does to help other people that look at it.

In the program class Game game = new Game(); doesn't really need to be there as you don't use it in the code. Sticks to naming conventions.

In the testing class runningtest could be put in PascalCase as it is a method, Debug.Assert() is used correctly.

All in all, the code is easy to understand and meets the brief requirements. It creates 3 dice, rolls them, reports the numbers etc etc.

**Comment by ardentsolitude** [comment]
Code is well formatted and runs without errors. Everything is commented well and is easy to understand the function of, however there are no XML comments to help explain the purposes of functions. The testing is well done, making good use of Debug.Assert to identify potential errors.

Overall, your code is easy to read and understand, is well formatted, meets all the given requirements, and runs without error.

**Review by ThomGitHub — COMMENTED** [review]
**Have the requirements been met?** The basic requirements of the game's functionality have been met; the game rolls three dice, shows the value of the dice roll and then the sum of the dice together. However, XML comments for documentation purposes are missing.

**Is the code formatted using the Style Guidelines correctly?** Variables are named within Camel Case and the code generally follows the Microsoft Style Guidelines correctly, however, it stipulates that comments should be placed the line after the code, rather than at the end of a line of code.

**Is the code easy to read?** The code is easy to read, with logic simply laid out and the different classes of the code fitting together well. However, code is written repetitively at points, consider using loops in place of repeating lines.

**Are different errors handled correctly?** The program leaves little room for errors, only relying on a few simplistic calculations in order to function. To ensure the accuracy of these calculations, Debug.Asset() is used within Testing—as requested by the brief.

**Pull request merged**
